algorithm: fedavg
dataset: cinic10
model: resnet34

set_seed: true
seed: 16


client_num: 100

batch_size: 256 # trainloader batch size
t_batch_size: 2048 # testloader batch size

client_join_ratio: 0.3
global_epoch: 300
local_epoch: 4

# optimizer
lr: 0.01
momentum: 0.0
weight_decay: 0.0

save_log: 1
# wandb setting
wandb: 1 # wandb: 1 record, 0 not
project: cinic10_16
experiment_name: fedavg_256


client_eval: false

device: cuda:0

