algorithm: FedTT
dataset: cinic10
model: resnet34

set_seed: true
seed: 16


client_num: 100

batch_size: 128 # trainloader batch size
t_batch_size: 2048 # testloader batch size

client_join_ratio: 0.3 # Each time, client_join_ratio * client_num clients are selected to participate in training.
global_epoch: 300
local_epoch: 4

# parameter for torch.optim.SGD
lr: 0.01
momentum: 0.0
weight_decay: 0.0


# wandb setting
wandb: 1 # wandb: 1 record, 0 not
project: cinic10_16
experiment_name: FedTT_r1

r: 0.1 # retention rate

max_gpu_memory_GB: 22

client_eval: false # Whether to perform testing on the client side.
save_log: 1 # Store output logs locally.
device: cuda:0

