algorithm: FedTT
batch_size: 128
client_eval: false
client_join_ratio: 0.3
client_num: 100
dataset: cinic10
device: cuda:0
experiment_name: FedTT_r3_128
global_epoch: 300
local_epoch: 4
lr: 0.01
max_gpu_memory_GB: 22
model: resnet34
momentum: 0.0
project: cinic10_166
r: 0.3
save_log: 1
seed: 166
set_seed: true
t_batch_size: 2048
wandb: 1
weight_decay: 0.0
