algorithm: fedavg
model: resnet18 # resnet18、
dataset: cifar100 #cinic10、


server_ip: "172.18.101.107"
server_port: 65431

set_seed: True # True为设置种子，False为性能测试
seed: 16 # 注意修改data中的seed;

need_connect_device: 3
client_num: 30 #客户端数量
client_join_ratio: 0.3 #Ratio for (client each round) / (client num in total).
global_epoch: 300
local_epoch: 4
batch_size: 64 # Data batch size for client local training.
t_batch_size: 256
client_eval: False

lr: 0.01 # Learning rate for client local training.
momentum: 0.0 # Momentum for client local opitimizer.
weight_decay: 0.0 # Weight decay for client local optimizer.

# record
save_log: 1 # Non-zero value for saving algorithm running log 

# wandb记录
wandb: 1
project: "resnet18_cifar100_on_device"
experiment_name: "fedavg"
