algorithm: ODE
dataset: snli 
model: biRNN 


set_seed: True 
seed: 16 

client_num: 100
client_join_ratio: 0.3 #Ratio for (client each round) / (client num in total).

global_epoch: 300
local_epoch: 4

batch_size: 256 # trainloader batch size
t_batch_size: 2048 # testloader batch size

# parameter for torch.optim.SGD
lr: 0.01 # Learning rate for client local training.
momentum: 0.0 # Momentum for client local opitimizer.
weight_decay: 0.0 # Weight decay for client local optimizer.


# wandb record
wandb: 1 # wandb: 1 record, 0 not
project: snli_16
experiment_name: ODE

labels_per_client: 1.0 # parameter for ode
update_batch_size: 64 # parameter for ode

client_eval: False # Whether to perform testing on the client side.
save_log: 1 # Non-zero value for saving algorithm running log 
device: "cuda:0"
