R_S: 0.9
algorithm: fedcase
alpha: 0.0
batch_size: 256
client_eval: false
client_join_ratio: 0.3
client_num: 100
dataset: cinic10
device: cuda:0
experiment_name: fedcase_256
global_epoch: 300
local_epoch: 4
lr: 0.01
model: resnet34
momentum: 0.0
project: cinic10_16666
save_log: 1
seed: 16666
set_seed: true
t_batch_size: 2048
wandb: 1
weight_decay: 0.0
