algorithm: centralized
model: vit 
dataset: domainnet 


set_seed: True # True为设置种子，False为性能测试
seed: 1666 # 注意修改data中的seed;


global_epoch: 10
batch_size: 64 # Data batch size for client local training.
t_batch_size: 512

lr: 0.01 # Learning rate for client local training.
momentum: 0.0 # Momentum for client local opitimizer.
weight_decay: 0.0 # Weight decay for client local optimizer.


# wandb记录
wandb: 1
project: "vit_domainnet_1666_dir_1"
experiment_name: "centralized training"
