algorithm: centralized
model: vit 
dataset: domainnet 


set_seed: True 
seed: 166666


global_epoch: 10
batch_size: 64 # Data batch size for client local training.
t_batch_size: 512

lr: 0.01 # Learning rate for client local training.
momentum: 0.0 # Momentum for client local opitimizer.
weight_decay: 0.0 # Weight decay for client local optimizer.


# wandb record
wandb: 1
project: "domainnet_166666"
experiment_name: "centralized training"
device: "cuda:0"
