dataset: domainnet
seed: 166666 

client_num: 30 

iid: 0 # 0: non-iid, others: iid
alpha: 0.05 # if non-iid, Dirichlet distribution

least_samples: 100 # Each client has at least least_samples samples.
device: "cuda:0"
