algorithm: centralized
dataset: domainnet 
model: vit 


set_seed: True 
seed: 166


global_epoch: 100
batch_size: 64 # trainloader batch size
t_batch_size: 512 # testloader batch size

# parameter for torch.optim.SGD
lr: 0.01 # Learning rate for client local training.
momentum: 0.0 # Momentum for client local opitimizer.
weight_decay: 0.0 # Weight decay for client local optimizer.


# wandb record
wandb: 0 # wandb: 1 record, 0 not
project: domainnet_166
experiment_name: centralized training
device: "cuda:1"
